/**
 * Do not edit this file
 *
 * To see how to use the main executable, compile with make and run ./main -h
 * Or if your code doesn't compile, see the parse_cli function body in utils.c,
 * which prints the help message
 */

#include <stdio.h>
#include <stdlib.h>

#include "instructions.h"
#include "utils.h"

int run_main(int argc, char* argv[]) {
    cli_args args = parse_cli(argc, argv);

    uint32_t instructions[MAX_INSTRUCTIONS] = {0};
    int32_t registers[NUM_REGISTERS] = {0};
    uint32_t pc = INITIAL_PC;

    uint32_t num_instructions =
        hex_instruction_file_to_array(args.filepath, instructions);

    execute_all(instructions, num_instructions, registers, &pc, args);

    free(args.filepath);

    return EXIT_SUCCESS;
}

/**
 * tests.cpp needs to test this
 * However, GTest tests executable already defines a main function so can't
 * include this
 * In Makefile, for tests executable, this is compiled with flag -DTEST_MODE
 * to exclude main function
 */
#ifndef TEST_MODE

int main(int argc, char* argv[]) { return run_main(argc, argv); }

#endif  // TEST_MODE
